/*
===============================================================================
Stored Procedure: bronze.load_bronze
===============================================================================
Procedure Purpose:
    Loads CSV data files into the bronze layer tables for the Kenyan Retail
    Market Basket Analysis project. This procedure serves as the data ingestion
    pipeline from raw CSV files to the staging database.
    
    Key Features:
    - Bulk loads 11 tables from CSV files
    - Maintains proper loading order to respect dependencies
    - Includes comprehensive error handling and logging
    - Provides detailed execution summary
    - Handles optional tables gracefully
    
Database Context:
    - Schema: bronze (raw data staging)
    - File Location: C:\Users\HomePC\Desktop\data science\Market Basket Analysis\bronze\bronze\
    - File Format: CSV with headers, comma-separated, CRLF line endings
    
Execution Instructions:
    1. Ensure CSV files exist in the designated directory
    2. Execute: EXEC bronze.run_data_load
    3. Monitor output for success/failure messages
    
Dependencies:
    - bronze schema and tables must exist (run DDL script first)
    - CSV files must be generated by Python data generation scripts
    - File system permissions for BULK INSERT operations
    
Error Handling:
    - Comprehensive TRY-CATCH blocks for each table load
    - Detailed error messages with troubleshooting tips
    - Graceful handling of missing optional tables/files
    
Author: [Your Name/Team]
Version: 1.1
Created: 2025-12-23
Last Modified: 2025-12-23
===============================================================================
*/
CREATE OR ALTER PROCEDURE bronze.load_bronze AS 
BEGIN 
    -- =======================================================================
    -- DECLARE VARIABLES
    -- =======================================================================
    DECLARE @start_time DATETIME, @end_time DATETIME  -- Timing variables
    DECLARE @gis_counties_count INT, @gis_locations_count INT, @stores_count INT
    DECLARE @hr_count INT, @crm_count INT, @pos_count INT, @products_count INT
    DECLARE @competitors_count INT, @competitor_stores_count INT, @economic_count INT
    DECLARE @employee_shifts_count INT  -- Row count variables for each table
    
    SET @start_time = GETDATE()  -- Record start time for performance tracking
    
    BEGIN TRY
        PRINT '==============================================================';
        PRINT 'STARTING BRONZE DATA LOAD';
        PRINT '==============================================================';
        
        -- ===================================================================
        -- DEFINE FILE PATHS
        -- ===================================================================
        DECLARE @base_path NVARCHAR(500)
        SET @base_path = 'C:\Users\HomePC\Desktop\data science\Market Basket Analysis\bronze\bronze\'
        -- Note: All CSV files should be in this directory
        
        -- ===================================================================
        -- 1. LOAD GIS COUNTIES DATA (Independent foundational data)
        -- ===================================================================
        TRUNCATE TABLE bronze.gis_counties_raw;
        PRINT '>>> Inserting table: bronze.gis_counties_raw <<<';
        EXEC('
        BULK INSERT bronze.gis_counties_raw
        FROM ''' + @base_path + 'gis_counties_raw.csv''
        WITH (
            FIRSTROW = 2,            -- Skip header row
            FIELDTERMINATOR = '','',  -- Comma-separated values
            ROWTERMINATOR = ''0x0a'', -- Line feed terminator
            TABLOCK                  -- Table lock for performance
        )');
        SET @gis_counties_count = @@ROWCOUNT;
        PRINT '   ' + CAST(@gis_counties_count AS NVARCHAR) + ' rows loaded';
        
        -- ===================================================================
        -- 2. LOAD GIS LOCATIONS DATA (Depends on counties reference data)
        -- ===================================================================
        TRUNCATE TABLE bronze.gis_locations_raw;
        PRINT '>>> Inserting table: bronze.gis_locations_raw <<<';
        EXEC('
        BULK INSERT bronze.gis_locations_raw
        FROM ''' + @base_path + 'gis_locations_raw.csv''
        WITH (
            FIRSTROW = 2,
            FIELDTERMINATOR = '','',
            ROWTERMINATOR = ''0x0a'',
            TABLOCK
        )');
        SET @gis_locations_count = @@ROWCOUNT;
        PRINT '   ' + CAST(@gis_locations_count AS NVARCHAR) + ' rows loaded';
        
        -- ===================================================================
        -- 3. LOAD STORES DATA (Foundational for HR and POS integration)
        -- ===================================================================
        TRUNCATE TABLE bronze.stores_raw;
        PRINT '>>> Inserting table: bronze.stores_raw <<<';
        EXEC('
        BULK INSERT bronze.stores_raw
        FROM ''' + @base_path + 'stores_raw.csv''
        WITH (
            FIRSTROW = 2,
            FIELDTERMINATOR = '','',
            ROWTERMINATOR = ''0x0a'',
            TABLOCK
        )');
        SET @stores_count = @@ROWCOUNT;
        PRINT '   ' + CAST(@stores_count AS NVARCHAR) + ' rows loaded';
        
        -- ===================================================================
        -- 4. LOAD HR DATA (CRITICAL - Must load before POS for cashier IDs)
        -- ===================================================================
        TRUNCATE TABLE bronze.hr_raw;
        PRINT '>>> Inserting table: bronze.hr_raw <<<';
        PRINT '   IMPORTANT: HR data provides employee IDs for POS transactions';
        EXEC('
        BULK INSERT bronze.hr_raw
        FROM ''' + @base_path + 'hr_raw.csv''
        WITH (
            FIRSTROW = 2,
            FIELDTERMINATOR = '','',
            ROWTERMINATOR = ''0x0a'',
            TABLOCK
        )');
        SET @hr_count = @@ROWCOUNT;
        PRINT '   ' + CAST(@hr_count AS NVARCHAR) + ' rows loaded';
        
        -- ===================================================================
        -- 5. LOAD CRM DATA (Customer master for POS transactions)
        -- ===================================================================
        TRUNCATE TABLE bronze.crm_raw;
        PRINT '>>> Inserting table: bronze.crm_raw <<<';
        EXEC('
        BULK INSERT bronze.crm_raw
        FROM ''' + @base_path + 'crm_raw.csv''
        WITH (
            FIRSTROW = 2,
            FIELDTERMINATOR = '','',
            ROWTERMINATOR = ''0x0a'',
            TABLOCK
        )');
        SET @crm_count = @@ROWCOUNT;
        PRINT '   ' + CAST(@crm_count AS NVARCHAR) + ' rows loaded';
        
        -- ===================================================================
        -- 6. LOAD POS DATA (Depends on HR, Stores, and CRM data)
        -- ===================================================================
        TRUNCATE TABLE bronze.pos_raw;
        PRINT '>>> Inserting table: bronze.pos_raw <<<';
        PRINT '   IMPORTANT: Links to HR (staff_id), Stores (store_id), CRM (customer_id)';
        EXEC('
        BULK INSERT bronze.pos_raw
        FROM ''' + @base_path + 'pos_raw.csv''
        WITH (
            FIRSTROW = 2,
            FIELDTERMINATOR = '','',
            ROWTERMINATOR = ''0x0a'',
            TABLOCK
        )');
        SET @pos_count = @@ROWCOUNT;
        PRINT '   ' + CAST(@pos_count AS NVARCHAR) + ' rows loaded';
        
        -- ===================================================================
        -- 7. LOAD PRODUCTS DATA (Optional but recommended for analysis)
        -- ===================================================================
        SET @products_count = 0;
        IF OBJECT_ID('bronze.products_raw','U') IS NOT NULL
        BEGIN
            TRUNCATE TABLE bronze.products_raw;
            PRINT '>>> Inserting table: bronze.products_raw <<<';
            PRINT '   NOTE: Products data enriches POS analysis with product details';
            
            BEGIN TRY
                EXEC('
                BULK INSERT bronze.products_raw
                FROM ''' + @base_path + 'products_raw.csv''
                WITH (
                    FIRSTROW = 2,
                    FIELDTERMINATOR = '','',
                    ROWTERMINATOR = ''0x0a'',
                    TABLOCK
                )');
                SET @products_count = @@ROWCOUNT;
                PRINT '   ' + CAST(@products_count AS NVARCHAR) + ' rows loaded';
            END TRY
            BEGIN CATCH
                PRINT '   WARNING: Could not load products_raw.csv - ' + ERROR_MESSAGE();
                PRINT '   Ensure the file exists and run products_raw.py first';
            END CATCH
        END
        ELSE
        BEGIN
            PRINT '>>> Skipping bronze.products_raw (table does not exist) <<<';
        END
        
        -- ===================================================================
        -- 8. LOAD COMPETITORS DATA (External reference data)
        -- ===================================================================
        TRUNCATE TABLE bronze.competitors_raw;
        PRINT '>>> Inserting table: bronze.competitors_raw <<<';
        EXEC('
        BULK INSERT bronze.competitors_raw
        FROM ''' + @base_path + 'competitors_raw.csv''
        WITH (
            FIRSTROW = 2,
            FIELDTERMINATOR = '','',
            ROWTERMINATOR = ''0x0a'',
            TABLOCK
        )');
        SET @competitors_count = @@ROWCOUNT;
        PRINT '   ' + CAST(@competitors_count AS NVARCHAR) + ' rows loaded';
        
        -- ===================================================================
        -- 9. LOAD COMPETITOR STORES DATA (Depends on competitors data)
        -- ===================================================================
        TRUNCATE TABLE bronze.competitor_stores_raw;
        PRINT '>>> Inserting table: bronze.competitor_stores_raw <<<';
        EXEC('
        BULK INSERT bronze.competitor_stores_raw
        FROM ''' + @base_path + 'competitor_stores_raw.csv''
        WITH (
            FIRSTROW = 2,
            FIELDTERMINATOR = '','',
            ROWTERMINATOR = ''0x0a'',
            TABLOCK
        )');
        SET @competitor_stores_count = @@ROWCOUNT;
        PRINT '   ' + CAST(@competitor_stores_count AS NVARCHAR) + ' rows loaded';
        
        -- ===================================================================
        -- 10. LOAD ECONOMIC DATA (Time-series market data)
        -- ===================================================================
        TRUNCATE TABLE bronze.economic_raw;
        PRINT '>>> Inserting table: bronze.economic_raw <<<';
        EXEC('
        BULK INSERT bronze.economic_raw
        FROM ''' + @base_path + 'economic_raw.csv''
        WITH (
            FIRSTROW = 2,
            FIELDTERMINATOR = '','',
            ROWTERMINATOR = ''0x0a'',
            TABLOCK
        )');
        SET @economic_count = @@ROWCOUNT;
        PRINT '   ' + CAST(@economic_count AS NVARCHAR) + ' rows loaded';
        
        -- ===================================================================
        -- 11. LOAD EMPLOYEE SHIFTS DATA (Optional, for detailed HR-POS integration)
        -- ===================================================================
        SET @employee_shifts_count = 0;
        IF OBJECT_ID('bronze.employee_shifts_raw','U') IS NOT NULL
        BEGIN
            TRUNCATE TABLE bronze.employee_shifts_raw;
            PRINT '>>> Inserting table: bronze.employee_shifts_raw <<<';
            PRINT '   NOTE: Detailed shift data for HR-POS integration analysis';
            
            BEGIN TRY
                EXEC('
                BULK INSERT bronze.employee_shifts_raw
                FROM ''' + @base_path + 'employee_shifts_raw.csv''
                WITH (
                    FIRSTROW = 2,
                    FIELDTERMINATOR = '','',
                    ROWTERMINATOR = ''0x0a'',
                    TABLOCK
                )');
                SET @employee_shifts_count = @@ROWCOUNT;
                PRINT '   ' + CAST(@employee_shifts_count AS NVARCHAR) + ' rows loaded';
            END TRY
            BEGIN CATCH
                PRINT '   WARNING: Could not load employee_shifts_raw.csv - ' + ERROR_MESSAGE();
                PRINT '   Ensure the file exists and run employee_shifts_raw.py first';
            END CATCH
        END
        ELSE
        BEGIN
            PRINT '>>> Skipping bronze.employee_shifts_raw (table does not exist) <<<';
        END
        
        -- ===================================================================
        -- EXECUTION SUMMARY
        -- ===================================================================
        SET @end_time = GETDATE()
        
        PRINT '';
        PRINT '==============================================================';
        PRINT 'BRONZE DATA LOAD SUMMARY';
        PRINT '==============================================================';
        PRINT 'Table                 | Rows Loaded';
        PRINT '----------------------|------------';
        PRINT 'gis_counties_raw      | ' + CAST(@gis_counties_count AS NVARCHAR);
        PRINT 'gis_locations_raw     | ' + CAST(@gis_locations_count AS NVARCHAR);
        PRINT 'stores_raw            | ' + CAST(@stores_count AS NVARCHAR);
        PRINT 'hr_raw                | ' + CAST(@hr_count AS NVARCHAR);
        PRINT 'crm_raw               | ' + CAST(@crm_count AS NVARCHAR);
        PRINT 'pos_raw               | ' + CAST(@pos_count AS NVARCHAR);
        PRINT 'products_raw          | ' + CAST(@products_count AS NVARCHAR);
        PRINT 'competitors_raw       | ' + CAST(@competitors_count AS NVARCHAR);
        PRINT 'competitor_stores_raw | ' + CAST(@competitor_stores_count AS NVARCHAR);
        PRINT 'economic_raw          | ' + CAST(@economic_count AS NVARCHAR);
        IF @employee_shifts_count > 0
            PRINT 'employee_shifts_raw   | ' + CAST(@employee_shifts_count AS NVARCHAR);
        
        PRINT '';
        PRINT '==============================================================';
        PRINT 'BRONZE DATA LOAD COMPLETE';
        PRINT '==============================================================';
        PRINT 'Total duration: ' + CAST(DATEDIFF(second, @start_time, @end_time) AS NVARCHAR) + ' seconds';
        DECLARE @tables_loaded INT = 10;
        IF @products_count > 0 SET @tables_loaded = @tables_loaded + 1;
        IF @employee_shifts_count > 0 SET @tables_loaded = @tables_loaded + 1;
        PRINT 'Total tables loaded: ' + CAST(@tables_loaded AS NVARCHAR) + ' (2 optional tables may be skipped)';
        PRINT '';
        PRINT 'KEY RELATIONSHIPS ESTABLISHED:';
        PRINT '  • HR → POS: hr_raw.employee_id → pos_raw.staff_id (cashiers)';
        PRINT '  • Stores → HR: stores_raw.store_id → hr_raw.store_id (store employees)';
        PRINT '  • Stores → POS: stores_raw.store_id → pos_raw.store_id (transactions)';
        PRINT '  • CRM → POS: crm_raw.customer_id → pos_raw.customer_id (customers)';
        IF @products_count > 0
            PRINT '  • Products → POS: products_raw.product_id → pos_raw.product_id';
        PRINT '==============================================================';
        
    END TRY
    BEGIN CATCH
        -- ===================================================================
        -- ERROR HANDLING
        -- ===================================================================
        PRINT '========================================================';
        PRINT 'ERROR OCCURRED WHILE LOADING DATA';
        PRINT '========================================================';
        PRINT 'Error Message: ' + ERROR_MESSAGE();
        PRINT 'Error Line: ' + CAST(ERROR_LINE() AS NVARCHAR);
        PRINT 'Error Procedure: ' + COALESCE(ERROR_PROCEDURE(), 'N/A');
        PRINT '========================================================';
        
        -- Determine which table likely caused the failure
        DECLARE @current_table NVARCHAR(100)
        SET @current_table = 
            CASE 
                WHEN ERROR_MESSAGE() LIKE '%bronze.gis_counties_raw%' THEN 'gis_counties_raw'
                WHEN ERROR_MESSAGE() LIKE '%bronze.gis_locations_raw%' THEN 'gis_locations_raw'
                WHEN ERROR_MESSAGE() LIKE '%bronze.stores_raw%' THEN 'stores_raw'
                WHEN ERROR_MESSAGE() LIKE '%bronze.hr_raw%' THEN 'hr_raw'
                WHEN ERROR_MESSAGE() LIKE '%bronze.crm_raw%' THEN 'crm_raw'
                WHEN ERROR_MESSAGE() LIKE '%bronze.pos_raw%' THEN 'pos_raw'
                WHEN ERROR_MESSAGE() LIKE '%bronze.products_raw%' THEN 'products_raw'
                WHEN ERROR_MESSAGE() LIKE '%bronze.competitors_raw%' THEN 'competitors_raw'
                WHEN ERROR_MESSAGE() LIKE '%bronze.competitor_stores_raw%' THEN 'competitor_stores_raw'
                WHEN ERROR_MESSAGE() LIKE '%bronze.economic_raw%' THEN 'economic_raw'
                WHEN ERROR_MESSAGE() LIKE '%bronze.employee_shifts_raw%' THEN 'employee_shifts_raw'
                ELSE 'Unknown table'
            END
        
        PRINT 'Likely failed table: ' + @current_table;
        PRINT '========================================================';
        PRINT 'TROUBLESHOOTING TIPS:';
        PRINT '1. Check if CSV file exists at: ' + @base_path;
        PRINT '2. Verify CSV format matches table structure';
        PRINT '3. Check for special characters in CSV that may cause issues';
        PRINT '4. Ensure CSV has proper line endings (CRLF for Windows)';
        PRINT '5. Run Python scripts to generate missing files:';
        PRINT '   • python products_raw.py';
        PRINT '   • python employee_shifts_raw.py';
        PRINT '6. File path being used: ' + @base_path + 'filename.csv';
        PRINT '========================================================';
    END CATCH
END
GO

/*
===============================================================================
Stored Procedure: bronze.run_data_load
===============================================================================
Procedure Purpose:
    Simple wrapper procedure to execute the main bronze data load procedure.
    Provides a clean interface for users to run the data load process.
    
Usage:
    EXEC bronze.run_data_load
    
Parameters:
    None
    
Returns:
    Console output with execution status and summary
    
Author: [Your Name/Team]
Version: 1.0
===============================================================================
*/
CREATE OR ALTER PROCEDURE bronze.run_data_load AS
BEGIN
    PRINT 'Executing bronze data load procedure...';
    PRINT 'Start time: ' + CONVERT(NVARCHAR, GETDATE(), 120);
    EXEC bronze.load_bronze;
END
GO

-- ===========================================================================
-- FINAL SETUP MESSAGE
-- ===========================================================================
PRINT '==============================================================';
PRINT 'BRONZE LAYER LOAD PROCEDURES CREATED SUCCESSFULLY';
PRINT '==============================================================';
PRINT '';
PRINT 'SETUP COMPLETE:';
PRINT '✓ bronze schema and tables created';
PRINT '✓ bronze.load_bronze procedure created';
PRINT '✓ bronze.run_data_load wrapper procedure created';
PRINT '';
PRINT 'NEXT STEPS:';
PRINT '1. Ensure CSV files exist in:';
PRINT '   C:\Users\HomePC\Desktop\data science\Market Basket Analysis\bronze\bronze\';
PRINT '2. Execute data load: EXEC bronze.run_data_load';
PRINT '3. Verify data loaded successfully from summary output';
PRINT '';
PRINT 'FILE GENERATION (if missing):';
PRINT '1. Navigate to Scripts directory:';
PRINT '   cd "C:\Users\HomePC\Desktop\data science\Market Basket Analysis\bronze\Scripts"';
PRINT '2. Run Python scripts:';
PRINT '   python products_raw.py';
PRINT '   python employee_shifts_raw.py';
PRINT '3. Verify CSV files appear in the bronze\bronze\ directory';
PRINT '==============================================================';
